# DSP - Aufgabenblatt 4
#### FHNW - HS2021

## *NumPy*

Schreiben Sie, wo immer möglich und sinnvoll, für die Umsetzung der Aufgabenstellungen Funktionen. Führen Sie die Funktionen mittels `%timeit` aus. Versuchen Sie eine effiziente Implementierung zu finden.

### Aufgabe 1 - Kurzaufgaben

Erzeugen Sie für die folgenden Kurzaufgaben jeweils die notwendindigen *arrays*. Falls nicht genauer spezifiziert, erzuegen sie *arrays* mit ganzzahligen Zufallszahlen auf dem Intervall $[0, 9]$ mittels `np.random.randint`.

In [1]:
import numpy as np

1. Erzeugen Sie einen Vektor der Länge 10, mit überall Nullen, ausser bei Index 5. Hier soll der Wert 5 sein.

In [2]:
x = np.zeros(10,)
x[5] = 5
x

array([0., 0., 0., 0., 0., 5., 0., 0., 0., 0.])

2. Drehen Sie die Reihenfolge der Elemente eines *arrays* um.

In [3]:
x = np.arange(10)[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Weitere Möglichkeiten ein Array zu erzeugen:

In [4]:
# equally spaced on logarithmic scales
np.logspace(-3, 2, 10)

array([1.00000000e-03, 3.59381366e-03, 1.29154967e-02, 4.64158883e-02,
       1.66810054e-01, 5.99484250e-01, 2.15443469e+00, 7.74263683e+00,
       2.78255940e+01, 1.00000000e+02])

In [5]:
# equally spaced on linear scales
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

3. Geben Sie den Index desjenigen Wertes eines *arrays* zurück, welcher einer zu wählenden Zahl am nächsten ist.

In [6]:
# initialize an array first
x = np.arange(0,100, 13)

In [7]:
x

array([ 0, 13, 26, 39, 52, 65, 78, 91])

In [8]:
TARGET = 44
idx = np.argmin(np.abs(x - TARGET))
idx

3

4. Erzeugen Sie ein *array* der Grösse $(3 \times 3)$ mit den Werten $[0, 8]$.

In [9]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5. Geben Sie den benötigten Speicherplatz eines *arrays* aus, sowie eine einzelnen Elements.

In [10]:
# total memory size in bytes
x.nbytes

64

In [11]:
# memory size of one item
x.itemsize

8

In [12]:
# number of items
x.size

8

6. Erzeugen Sie ein $(3 \times 3 \times 3)$ *array* mit gleichverteilten Zufallszahlen auf dem Intervall $[0, 5]$.

In [13]:
np.random.uniform(5, size=(3,3,3))

array([[[1.07689781, 1.78661116, 4.18972218],
        [4.03021972, 1.87735521, 2.80282481],
        [1.78867581, 4.5664105 , 2.49012784]],

       [[4.47661735, 3.65645175, 4.00925506],
        [1.72574547, 1.36670971, 2.67836574],
        [3.72569072, 4.80136601, 1.52661108]],

       [[3.34041362, 3.69105903, 4.4295931 ],
        [1.34393451, 2.66874857, 1.15668453],
        [2.47776268, 2.30171852, 2.81987208]]])

7. Erzeugen Sie ein *array* der Grösse $(5 \times 5)$ mit den Elementen $[1,2,3,4,]$ auf der ersten unteren Nebendiagonalen.

In [14]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

8. Erzeugen Sie ein *array* der Grösse $(8 \times 8)$ und füllen Sie es mit einem Schachrettmuster der Zahlen $[0, 1]$.

In [15]:
x = np.zeros((8,8))
# indexing for all even rows and columns
x[::2, ::2] = 1
# indexing for all odd rows and columns
x[1::2, 1::2] = 1
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

9. Erzeugen Sie zwei *arrays* gleicher Grösse gefüllt mit ganzzahligen Zufallszahlen und finden Sie die Indices zu jenen Zellen, welche übereinstimmende Zahlen enthalten.  

    Wie können Sie überprüfen, ob die *arrays* gleich sind?

In [16]:
x = np.random.randint(10, size=(100))
y = np.random.randint(10, size=(100))

In [17]:
idx = np.where(x == y)[0]
idx

array([20, 26, 35, 45, 50, 54, 67])

In [18]:
# verify values at identified index positions
x[idx]

array([1, 0, 7, 4, 8, 2, 4])

In [19]:
y[idx]

array([1, 0, 7, 4, 8, 2, 4])

In [20]:
# comparison of the entire array
np.array_equal(x, y)

False

10. Ziehen Sie den Mittelwert sämtlicher Spalten von den Elementen jener Spalte ab.

In [4]:
X = np.random.randint(10, size=(10,12))
X

array([[9, 5, 6, 5, 2, 8, 4, 9, 3, 1, 2, 4],
       [6, 6, 4, 8, 2, 2, 6, 5, 6, 7, 5, 6],
       [9, 9, 9, 3, 5, 2, 6, 6, 8, 1, 7, 6],
       [1, 0, 4, 1, 9, 1, 4, 9, 8, 0, 5, 6],
       [0, 0, 5, 5, 8, 3, 4, 3, 9, 2, 5, 6],
       [6, 7, 1, 9, 7, 0, 9, 3, 7, 0, 3, 4],
       [0, 1, 1, 9, 7, 2, 0, 4, 4, 4, 2, 6],
       [0, 1, 1, 4, 9, 8, 7, 2, 0, 1, 2, 1],
       [4, 3, 5, 6, 8, 2, 7, 1, 2, 6, 4, 6],
       [1, 1, 2, 5, 8, 4, 2, 6, 5, 3, 4, 6]])

In [5]:
# this step employs broadcasting!
X - X.mean(axis=0)

array([[ 5.4,  1.7,  2.2, -0.5, -4.5,  4.8, -0.9,  4.2, -2.2, -1.5, -1.9,
        -1.1],
       [ 2.4,  2.7,  0.2,  2.5, -4.5, -1.2,  1.1,  0.2,  0.8,  4.5,  1.1,
         0.9],
       [ 5.4,  5.7,  5.2, -2.5, -1.5, -1.2,  1.1,  1.2,  2.8, -1.5,  3.1,
         0.9],
       [-2.6, -3.3,  0.2, -4.5,  2.5, -2.2, -0.9,  4.2,  2.8, -2.5,  1.1,
         0.9],
       [-3.6, -3.3,  1.2, -0.5,  1.5, -0.2, -0.9, -1.8,  3.8, -0.5,  1.1,
         0.9],
       [ 2.4,  3.7, -2.8,  3.5,  0.5, -3.2,  4.1, -1.8,  1.8, -2.5, -0.9,
        -1.1],
       [-3.6, -2.3, -2.8,  3.5,  0.5, -1.2, -4.9, -0.8, -1.2,  1.5, -1.9,
         0.9],
       [-3.6, -2.3, -2.8, -1.5,  2.5,  4.8,  2.1, -2.8, -5.2, -1.5, -1.9,
        -4.1],
       [ 0.4, -0.3,  1.2,  0.5,  1.5, -1.2,  2.1, -3.8, -3.2,  3.5,  0.1,
         0.9],
       [-2.6, -2.3, -1.8, -0.5,  1.5,  0.8, -2.9,  1.2, -0.2,  0.5,  0.1,
         0.9]])

11. Wie können Sie zwei Zeilen eines zwei-dimensionalen *arrays* vertauschen?

In [23]:
X = np.random.randint(10, size=(3, 5))
X

array([[4, 0, 7, 8, 5],
       [2, 9, 7, 8, 4],
       [9, 1, 4, 8, 7]])

In [24]:
# switch rows
X[[0, 1]] = X[[1,0]]
X

array([[2, 9, 7, 8, 4],
       [4, 0, 7, 8, 5],
       [9, 1, 4, 8, 7]])

12. Wie können Sie den Wert eines *boolean arrays* negieren?

In [25]:
# generate boolean array
b = X > 3
b

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [26]:
np.logical_not(b)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False]])

13. Berechnen Sie das Produkt eines Vektors mit einer Matrix, welche bloss $2$-en auf der Diagnolen hat.  
    Messen Sie die Länge des Vektors vor und nach der Transformation. Was stellen Sie fest?

In [27]:
# generating an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
v = np.array([2,3,4])
# generating a matrix with 2s on the diagonal
M = 2*np.eye(3)

In [29]:
# matrix multiplication
M.dot(v)

array([4., 6., 8.])

In [30]:
np.linalg.norm(v)

5.385164807134504

In [31]:
np.linalg.norm(M.dot(v))

10.770329614269007